apiVersion: apps/v1
kind: Deployment
metadata:
  name: payg-service
  labels:
    app: payg-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payg-service
  template:
    metadata:
      labels:
        app: payg-service
    spec:
      containers:
      - name: payg-service
        image: 
        ports:
        - containerPort: 7070
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "aws"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "13.234.35.36:9092"
        - name: SPRING_DATA_REDIS_HOST
          value: "13.234.35.36"
        - name: GATEWAY_URL
          value: "http://payg-service-lb"
        - name: PAYG_URL
          value: "http://payg-service-lb"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
---

apiVersion: v1
kind: Service
metadata:
  name: payg-service-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: payg-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070